apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchasebook
  labels:
    app: purchasebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchasebook
  template:
    metadata:
      labels:
        app: purchasebook
    spec:
      containers:
        - name: purchasebook
          image: "sbells/purchasebook:20250703"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
