apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: sbells/eureka:20250703
          ports:
            - containerPort: 8088
          readinessProbe:
            httpGet:
              path: /
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 10
